name: Tests
on: [push, pull_request]

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
  PYTHONPATH: src

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        python-version: ['3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev gcc
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"  # или ваш способ
        # Или явно
        pip install pytest pytest-asyncio pytest-cov httpx sqlalchemy asyncpg psycopg2-binary alembic
    
    - name: Wait for PostgreSQL
      run: |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready"
            break
          fi
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
    
    - name: Run database migrations
      run: |
        alembic upgrade head
      env:
        DATABASE_URL: ${{ env.DATABASE_URL }}
    
    - name: Run tests with pytest
      run: |
        python -m pytest tests/ \
          -v \
          --tb=short \
          --cov=src \
          --cov-report=xml \
          --asyncio-mode=auto \
          --maxfail=5
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: ./coverage.xml