"""Remove intext_id from files table

Revision ID: 06f1557cfe5f
Revises: ebe64494335c
Create Date: 2025-11-09 15:28:24.625023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f1557cfe5f'
down_revision: Union[str, Sequence[str], None] = 'ebe64494335c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'intext_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('intext_id', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
