"""Move releases to another directory

Revision ID: 140ac7bb33d8
Revises: f7bdfd02c9d8
Create Date: 2025-11-03 20:32:10.996226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140ac7bb33d8'
down_revision: Union[str, Sequence[str], None] = 'f7bdfd02c9d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
