"""Add employeemeetings table with corresponding  relationships

Revision ID: 20749b5952e6
Revises: d9bd21d3ffda
Create Date: 2025-11-11 01:44:15.344716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20749b5952e6'
down_revision: Union[str, Sequence[str], None] = 'd9bd21d3ffda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employeemeetings',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employeemeetings')
    # ### end Alembic commands ###
