"""Fix foreign keys in Task Model 3

Revision ID: 20d5ff189747
Revises: 20b9c1ca3365
Create Date: 2025-11-02 23:52:01.503896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d5ff189747'
down_revision: Union[str, Sequence[str], None] = '20b9c1ca3365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
