"""Add password column into Employees table

Revision ID: 266c45e4a2f5
Revises: c00ae939bc5a
Create Date: 2025-11-02 23:11:16.978852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266c45e4a2f5'
down_revision: Union[str, Sequence[str], None] = 'c00ae939bc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###
