"""Check

Revision ID: 27ca0a8c0937
Revises: 947077519d92
Create Date: 2025-11-08 23:45:51.861785

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "27ca0a8c0937"
down_revision: Union[str, Sequence[str], None] = "947077519d92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('files_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "source", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column(
            "extension", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="files_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "projects",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('projects_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("manager_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("release_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"], ["employees.id"], name="projects_manager_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["release_id"], ["releases.id"], name="projects_release_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["statuses.id"], name="projects_status_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="projects_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "employees",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('employees_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("lname", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("fname", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("mname", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("dob", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("schedule_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name="employees_role_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"], ["schedules.id"], name="employees_schedule_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="employees_pkey"),
        sa.UniqueConstraint(
            "email",
            name="employees_email_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "tasks",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('tasks_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("creator_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("executor_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["employees.id"], name="tasks_creator_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["executor_id"], ["employees.id"], name="tasks_executor_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="tasks_project_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["status_id"], ["statuses.id"], name="tasks_status_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="tasks_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "taskfiles",
        sa.Column("task_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("file_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("taskfiles_file_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("taskfiles_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("task_id", "file_id", name=op.f("taskfiles_pkey")),
    )
    op.create_table(
        "roles",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('roles_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "description", sa.VARCHAR(length=15), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="roles_pkey"),
        sa.UniqueConstraint(
            "description",
            name="roles_description_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "version", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["status_id"], ["statuses.id"], name=op.f("releases_status_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("releases_pkey")),
    )
    op.create_table(
        "employeedepartments",
        sa.Column("department_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("employee_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "office", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("employeedepartments_department_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("employeedepartments_employee_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "department_id", "employee_id", name=op.f("employeedepartments_pkey")
        ),
    )
    op.create_table(
        "statuses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("alias", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("statuses_pkey")),
        sa.UniqueConstraint(
            "alias",
            name=op.f("statuses_alias_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("lead_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["employees.id"], name=op.f("departments_lead_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("departments_pkey")),
    )
    op.create_table(
        "workhours",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('workhours_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("starttime", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column("endtime", postgresql.TIME(), autoincrement=False, nullable=False),
        sa.Column(
            "lunchbreak_start", postgresql.TIME(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "lunchbreak_end", postgresql.TIME(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="workhours_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("sun_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("mon_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tue_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("wed_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("thu_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("fri_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["fri_id"], ["workhours.id"], name=op.f("schedules_fri_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["mon_id"], ["workhours.id"], name=op.f("schedules_mon_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sat_id"], ["workhours.id"], name=op.f("schedules_sat_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sun_id"], ["workhours.id"], name=op.f("schedules_sun_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["thu_id"], ["workhours.id"], name=op.f("schedules_thu_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["tue_id"], ["workhours.id"], name=op.f("schedules_tue_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["wed_id"], ["workhours.id"], name=op.f("schedules_wed_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("schedules_pkey")),
    )
    # ### end Alembic commands ###
