"""Add name column into File table

Revision ID: 2e4bf94ab5c8
Revises: 0225f5ec0ebc
Create Date: 2025-11-09 02:13:45.594268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4bf94ab5c8'
down_revision: Union[str, Sequence[str], None] = '0225f5ec0ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'name')
    # ### end Alembic commands ###
