"""Add Many-to-Many tables models (Empl - Department, Task - File), File model moved to self owned dir

Revision ID: 32d2b51a2d40
Revises: 8e82eb72a7c8
Create Date: 2025-11-08 18:34:50.318328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d2b51a2d40'
down_revision: Union[str, Sequence[str], None] = '8e82eb72a7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
