"""Move statuses to another directory

Revision ID: 3fe7eb5a4285
Revises: fa28314cd80d
Create Date: 2025-11-03 02:51:26.317843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe7eb5a4285'
down_revision: Union[str, Sequence[str], None] = 'fa28314cd80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statuses', 'alias',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.create_unique_constraint(None, 'statuses', ['alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statuses', type_='unique')
    op.alter_column('statuses', 'alias',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
