"""Change fks and pks in EmployeeMeeting

Revision ID: 443be2f1e63b
Revises: 484e26323a1c
Create Date: 2025-11-11 01:24:54.092589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443be2f1e63b'
down_revision: Union[str, Sequence[str], None] = '484e26323a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
