"""Add employees.position column, make task.executor_id unnecessary

Revision ID: 4508eb78bee8
Revises: 06f1557cfe5f
Create Date: 2025-11-09 21:31:45.762937

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4508eb78bee8"
down_revision: Union[str, Sequence[str], None] = "06f1557cfe5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees", sa.Column("position", sa.String(length=256), nullable=True)
    )
    op.alter_column("tasks", "executor_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "executor_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("employees", "position")
    # ### end Alembic commands ###
