"""Add employee <- vacations relationship

Revision ID: 777af9ad9828
Revises: e40ea6b3829b
Create Date: 2025-11-10 02:58:28.232436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777af9ad9828'
down_revision: Union[str, Sequence[str], None] = 'e40ea6b3829b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
