"""Add Many-to-Many tables models (Empl - Department, Task - File)

Revision ID: 8e82eb72a7c8
Revises: 492f2e392e79
Create Date: 2025-11-08 18:28:33.992984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e82eb72a7c8'
down_revision: Union[str, Sequence[str], None] = '492f2e392e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
