"""Add employeemeetings table with corresponding  relationships

Revision ID: a3b6903c52d2
Revises: 443be2f1e63b
Create Date: 2025-11-11 01:41:21.119446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b6903c52d2'
down_revision: Union[str, Sequence[str], None] = '443be2f1e63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
