"""Add employees.position column, make task.executor_id unnecessary

Revision ID: ab4d09706c96
Revises: 4508eb78bee8
Create Date: 2025-11-09 21:38:56.529750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4d09706c96'
down_revision: Union[str, Sequence[str], None] = '4508eb78bee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
