"""Add password column into Employees table

Revision ID: c00ae939bc5a
Revises: 831b9309c5b0
Create Date: 2025-11-02 23:10:54.026180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00ae939bc5a'
down_revision: Union[str, Sequence[str], None] = '831b9309c5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
