"""Move roles to another directory

Revision ID: c9e923299c9e
Revises: cbf222b584f9
Create Date: 2025-11-03 19:25:43.491434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e923299c9e'
down_revision: Union[str, Sequence[str], None] = 'cbf222b584f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.create_unique_constraint(None, 'roles', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
