"""Add relationshiops between taskcomments and tasks

Revision ID: f04fe9e0a183
Revises: ead8876472c9
Create Date: 2025-11-16 22:42:11.710953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04fe9e0a183'
down_revision: Union[str, Sequence[str], None] = 'ead8876472c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
