"""Add employee <- vacations relationship

Revision ID: f9e33f9ff9bb
Revises: 777af9ad9828
Create Date: 2025-11-10 03:00:30.965880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e33f9ff9bb'
down_revision: Union[str, Sequence[str], None] = '777af9ad9828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
